services:
  - type: web
    name: hln-nieuwsmonitor
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r news-monitor/requirements.txt"
    startCommand: "python news-monitor/server.py"
    envVars:
      - key: NIEUWSMONITOR_USER
        value: hln
      - key: NIEUWSMONITOR_PASSWORD
        sync: false
